### ISSUE TITLE
render occurs even if not needed

### ISSUE THREAD

**Issue by Gavroche95** [Zverik/polytiles#11]
Hi,

In directory output mode, polytiles always render tiles even if tile already exists

polytiles include in my old Mapnik sources verbose those tiles as 'exists' and skip rendering them

Regards,
Bruno.

**Comment by Zverik** [comment]
It took a long time, but `--skip-existing` option is finally there :)

**Comment by Gavroche95** [comment]
Hi,

Here is a great news ^^

Having done some tests this morning and found strange behaviour, in fact it looks like data are retrieved from database before tiles are marked as "to-skip".
So, unfortunatly, there is no time gained in skipping existing as database request is the most significant time consumer.

Sorry for my bad English, I hope you understood what i wrote


Regards,
Bruno.

PS : thank you so much for your implication in that project
PPS : I have an idea to improve --skip-existing, should I open a new issue ?
