### ISSUE TITLE
Metatile rendering

### ISSUE THREAD

**Issue by Zverik** [Zverik/polytiles#8]
To improve rendering speed and make tiles look more like at osm.org etc., render NxN tiles at once, and split them into images.

**Comment by Gavroche95** [comment]
rendering tile 0/0/0 require meta=2
rendering tiles x/y/1 requires meta=4
In other words, not specifying --meta N do not produce levels 0 and 1 tiles

Improvment : ability to store tiles in meta format (not splitted) just like renderd, ie : 0/0/0/0/0/0.meta


Regards,
Bruno
